# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  test:
    docker:
      - image: node:12.13.0

    working_directory: ~/repo

    steps:
      - checkout

      - run: npm --global add pnpm

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pnpm-loal.yaml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: pnpm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "pnpm-lock.yaml" }}

      - run: npm build
      - run: npm test

  release:
    docker:
      # specify the version you desire here
      - image: node:12.13.0

    working_directory: ~/repo

    steps:
      - checkout

      - run: npm --global add pnpm

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pnpm-lock.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: pnpm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "pnpm-lock.lock" }}

      - run: npm build
      - run: npm release

workflows:
  version: 2
  build-deploy:
    jobs:
      - test
      - release:
          requires:
            - test
          filters:
            branches:
              only: master
